name: Build new image and Deploy it to Kubernetes

on:
  push:
    branches:
      - fb-github_ci

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  IMAGE: openindoor/front-api
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: cluster-1
  GKE_ZONE: europe-north1-a

jobs:
  setup-build-publish:
    name: Setup, Build, Publish
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Login to Docker Hub using helper
    -  name: Login to Docker Hub
       uses: docker/login-action@v1
       with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN    }}

    # Build the Docker image
    - name: Build
      run: |-
        #Pull the image to save the build time
        docker build \
          --tag "$IMAGE":"$GITHUB_SHA" \
          .

    # Push the Docker image to Google Container Registry
    - name: Publish
      run: |-
        docker push "$IMAGE":"$GITHUB_SHA"

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: setup-build-publish

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Setup gcloud CLI
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@0.1.3
      with:
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT }}

    # Get the GKE credentials so we can deploy to the cluster
    - run: |-
        gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"

    # Set up kustomize
    - name: Set up Kustomize
      run: |-
        curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
        chmod u+x ./kustomize

    # Deploy the Docker image to the GKE cluster
    - name: Deploy
      run: |-
        ./kustomize edit set image "$IMAGE":"$GITHUB_SHA"
        ./kustomize build . |
        kubectl apply -f -

        #kubectl get services -o wide
        kubectl get pods
